<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ5q0i10\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ5q0i10/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQ5q0i10.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQ5q0i10\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQ5q0i10\appProdProjectContainer([
    'container.build_hash' => 'Q5q0i10',
    'container.build_id' => 'fc602fc4',
    'container.build_time' => 1704209720,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ5q0i10');
